const mongoose = require('mongoose');

const billSchema = new mongoose.Schema({
    patient: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
    doctor: { type: mongoose.Schema.Types.ObjectId, ref: 'Doctor' }, // Optional, if generated by doc
    type: { type: String, enum: ['consultation', 'lab', 'pharmacy'], required: true },
    description: String,
    amount: { type: Number, required: true },
    status: { type: String, enum: ['pending', 'paid'], default: 'pending' },
    date: { type: Date, default: Date.now }
});

module.exports = mongoose.model('Bill', billSchema);
